global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Channels;
global using System.Threading.Tasks;
global using Discord;
global using Discord.Webhook;
global using Discord.WebSocket;
global using EeveeCore.Common;
global using EeveeCore.Database;
global using EeveeCore.Database.Models;
global using EeveeCore.Extensions;
global using EeveeCore.Services;
global using NonBlocking;
global using EventHandler = EeveeCore.Services.EventHandler;